application: linear-elastostatics
version: 0.2
language: C++
processes: 1

requirements:
	libraries:
	- name: Parallel Unstructured Mesh Infrastructure
	  version: latest
	  repo: https://github.com/SCOREC/core.git
	- name: GoogleTest
	  version: "1.7.0"
	  repo: https://github.com/YetAnotherMinion/googletest.git
	- name: MPICH
	  version: "3.1"
	  release: "4.fc21"
	  repo: "fedora/21/x86_64"
	- name: Xerces-C++
	  version: "3.1.2"
	- name: "PETSc"
	  version: "3.6.1.0"
	  repo: "git clone -b maint https://bitbucket.org/petsc/petsc petsc"
