language: cpp
#run on latest container based infrastructure
sudo: false

branches:
  - master

compiler:
# don't build with clang until we can get a c++11 version
#  - clang
  - gcc

cache:
  - /tmp/packages

#workaround for container based packages
addons:
  apt:
    packages:
      - gfortran        # used by all
      - openmpi-bin     # -+
      - openmpi-common  #  | all for openmpi
      - libopenmpi-dev  # -+
      - mpich2          # -+
      - libmpich2-3     #  | all for mpich2
      - libmpich2-dev   # -+

env:
  - MPI_VENDOR=openmpi
# right now multiple versions of mpi do not work
#  - MPI_VENDOR=mpich2
  - DEP_DIR=/tmp
before_install:
  - export MAIN_DIR=$PWD
  - mkdir a1/obj a2/obj a3/obj a4/obj #create all needed dirs before any other steps 
  - mkdir a1/bin a2/bin a3/bin a4/bin
  - mkdir lib #use one folder at project root for lib

install:
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir /tmp/cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C /tmp/cmake
      export PATH=/tmp/cmake/bin:${PATH}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - which cmake
  ############################################################################
  # Install PETSc, MPICH2, PUMI, BLAS, LAPACK, SOWING, SuperLU
  ############################################################################
  - ./sbin/install_dependencies.sh -c -p ${DEP_DIR}
  #create the bin directories
  - touch travis_config.mk
  - echo -e 'ifeq ($(CC), gcc)\n\tMPIFLAGS+=--std=c++0x -Wno-long-long\nelse\n\tMPIFLAGS+=-Wno-c++11-long-long\nendif\nPETSC_DIR=/tmp/packages/petsc-3.6.1\nLDIR=$(MAIN_DIR)/lib\nPUMI_DIR=$(LDIR)/pumi\nGTEST_DIR=/tmp/googletest' > travis_config.mk
  - cat travis_config.mk | tee a1/config.mk a2/config.mk a3/config.mk a4/config.mk
  - MPIEXEC='mpiexec'
  - test $MPI_VENDOR == mpich2 && MPIEXEC='mpiexec -launcher fork' || true
  - mpiexec --version
  - make -C a1
  - make -C a2
  - make -C a3
  - make -C a4

before_script:
  #currently the a1 code has hardcoded filenames, so we need to move the meshes
  #into the correct directory
  - cp ${DEP_DIR}/src/test_meshes/a1/cube.dmg ./a1/
  - cp ${DEP_DIR}/src/test_meshes/a1/mixed-mesh-10.smb ./a1/
  - cp ${DEP_DIR}/src/test_meshes/a1/tet-mesh-10.smb ./a1/
script:
  #because of hardcoded file paths, must be in a1 directory
  - cd a1
  - mpirun ./bin/a1tet
  - mpirun ./bin/a1quad
  - mpirun ./bin/a1mix
  - cd ..
  #probably should use mpi run, however not worrying about it now
  - mpirun ./a2/bin/a2 ${DEP_DIR}/src/test_meshes/a2/reorder_a.dmg ${DEP_DIR}/src/test_meshes/a2/reorder_a.smb
  - mpirun ./a2/bin/a2 ${DEP_DIR}/src/test_meshes/a2/reorder_b.dmg ${DEP_DIR}/src/test_meshes/a2/reorder_b.smb
  - mpirun ./a2/bin/a2 ${DEP_DIR}/src/test_meshes/a2/reorder_c.dmg ${DEP_DIR}/src/test_meshes/a2/reorder_c.smb
  - ./a4/bin/app_test
  - ./a4/bin/convergence_test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c42da23dc9f9ae61b63d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always



