language: cpp
#run on latest container based infrastructure
sudo: false

compiler:
  - clang
  - gcc

#workaround for container based packages
addons:
  apt:
    packages:
      - openmpi
      - mpich

before_install:
  - echo "not using sudo"
#  - apt-get install -q gfortran openmpi-bin openmpi-common libopenmpi-dev;

#create the bin directories
before_script:


script: echo -e "foo"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c42da23dc9f9ae61b63d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always



