#!/bin/bash

set -eu
self=$(basename "$0")

case $# in
    1)
        DEP_DIR=$(readlink -f $1)
        ;;
    *)
        echo "usage: ${self} <install_prefix>"
        exit 0
        ;;
esac

echo -e "
PATH=${DEP_DIR}/bin:\$PATH
CC=\${CC:-gcc}
CXX=\${CXX:-g++}
"

